<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findMyGame($myId) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.player1 = :myId OR c.player2 = :myId')
                ->setParameters(array('myId' => $myId))
                ->setMaxResults(1);

        return $qb->getQuery()
                        ->getOneOrNullResult();
    }
    
    public function findMyGames($myId) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.player1 = :myId OR c.player2 = :myId')
                ->setParameters(array('myId' => $myId))
                ->setMaxResults(1);

        return $qb->getQuery()
                        ->getResult();
    }
}
