<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveRepository extends EntityRepository
{
    public function findNewMove($gameId, $oppId) {

        $qb = $this->createQueryBuilder('m');
        $result = $qb->select('m', 'g')
                ->leftjoin('m.game', 'g')
                ->where('g.id = :gameId', 'm.status = :status', 'm.playerId = :playerId')
                ->setParameters(array('gameId' => $gameId, 'status' => 'new', 'playerId' => $oppId,))
                ->setMaxResults(1)
                ->getQuery()
                ->getResult();
        return $result;
    }
}
