<?php

namespace AppBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll() {
        $qb = $this->createQueryBuilder('c')
                ->select('count(c)')
                ->where('c.status = :status')
                ->setParameters(array('status' => 1));

        return $qb->getQuery()
                        ->getSingleScalarResult();
    }
    
    public function findOpponent($myId) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.status = :status', 'c.id != :myId')
                ->setParameters(array('status' => 2, 'myId' => $myId))
                ->setMaxResults(1);

        return $qb->getQuery()
                        ->getOneOrNullResult();
    }
    
    
}
